### ISSUE TITLE
Website View

### ISSUE THREAD

**Issue by NikSchaefer** [ljosberinn/awesome-dev-discord#17]
Created a searchable website view for this data
[Deployment](https://dev-discords.now.sh/) :)
[Github](https://github.com/NikSchaefer/dev-discords)

**Comment by ljosberinn** [comment]
wow nice, didn't expect that :D I'll add it as website link here instead of the tweet if you don't mind?

**Comment by NikSchaefer** [comment]
Yeah that would be great!

**Comment by ljosberinn** [comment]
done, thank you :)

**Comment by ljosberinn** [comment]
do I know you from discord by the way? :o

**Comment by NikSchaefer** [comment]
I am in a variety of discords which is how I found you but I don't believe we've talked
